services:
  http:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - './:/app/'
      - '.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - php

  php:
    build:
      context: .docker/php
    volumes:
      - ./:/app/
    working_dir: /app/
    depends_on:
      - mysql

  node:
    image: node:20-alpine
    volumes:
      - ./:/app/
    working_dir: /app/
    entrypoint: [ 'npm', 'run', 'dev' ]
    ports:
      - '5173:5173'

  mysql:
    image: mysql:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

volumes:
  mysql-data:
